In [24]:
import torch

In [25]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [26]:
x.shape

torch.Size([12])

In [27]:
# x the number of element 
x.numel()

12

In [28]:
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [29]:
x.reshape(3, 4)
# x.shape(-1, 4), 自动推导行数

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [30]:
torch.zeros((2, 3, 4)) # 两个三行四列零矩阵


tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [31]:
torch.ones((2, 3, 4)) 

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [32]:
x = torch.randn(3, 4) # 三行四列张量，均值为零，标准差为1
print(x, torch.mean(x), torch.var(x))

tensor([[ 0.3362, -0.0406,  0.8100,  0.0427],
        [-0.6450,  1.5980,  2.2067,  0.7177],
        [ 0.5392, -0.6257, -1.4722,  0.7266]]) tensor(0.3495) tensor(1.0035)


In [33]:
torch.tensor([[2, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

In [34]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

In [35]:
torch.exp(x) # e^x

tensor([2.7183e+00, 7.3891e+00, 5.4598e+01, 2.9810e+03])

In [36]:
x = torch.arange(12, dtype=torch.float32).reshape((3, 4))
print('x =', x)
y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
print('y =', y)

print(torch.cat((x, y), dim=0), torch.cat((x, y), dim=1))

x = tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.]])
y = tensor([[2., 1., 4., 3.],
        [1., 2., 3., 4.],
        [4., 3., 2., 1.]])
tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [ 2.,  1.,  4.,  3.],
        [ 1.,  2.,  3.,  4.],
        [ 4.,  3.,  2.,  1.]]) tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
        [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
        [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]])


In [37]:
x.sum()

tensor(66.)

In [38]:
a = torch.arange(3).reshape((3, 1)) # 列向量3 * 1 
b = torch.arange(2).reshape((1, 2)) # 行向量1 * 2
a, b

(tensor([[0],
         [1],
         [2]]),
 tensor([[0, 1]]))

In [39]:
# a 复制列， a-> 3 * 2; b 复制行，b-> 3 * 2
a + b

tensor([[0, 1],
        [1, 2],
        [2, 3]])

In [40]:
# x的最后一个元素是一个数组
x[-1], x[1:3]

(tensor([ 8.,  9., 10., 11.]),
 tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

In [41]:
x = torch.zeros((3, 4))
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [42]:
# （1，2）
x[1, 2] = 1
x

tensor([[0., 0., 0., 0.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]])

In [43]:
x[0:1, :] = 9
x 

tensor([[9., 9., 9., 9.],
        [0., 0., 1., 0.],
        [0., 0., 0., 0.]])

In [44]:
a = x.numpy()
b = torch.tensor(a)
type(a), type(b)

(numpy.ndarray, torch.Tensor)