In [2]:
import torch

x = torch.tensor(3.0)
y = torch.tensor(2.0)

x + y, x * y, x / y, x ** y

(tensor(5.), tensor(6.), tensor(1.5000), tensor(9.))

In [3]:
a = torch.arange(4)
print(a, a[3])

print(len(a), a.shape)


tensor([0, 1, 2, 3]) tensor(3)
4 torch.Size([4])


In [4]:
a = torch.arange(20).reshape(5, -1)
print(a, '\n', a.T)

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19]]) 
 tensor([[ 0,  4,  8, 12, 16],
        [ 1,  5,  9, 13, 17],
        [ 2,  6, 10, 14, 18],
        [ 3,  7, 11, 15, 19]])


In [5]:
b = torch.tensor([[1, 2, 3], [2, 0, 4], [3, 4, 5]])
b == b.T

tensor([[True, True, True],
        [True, True, True],
        [True, True, True]])

In [6]:
a = torch.arange(20, dtype=torch.float32).reshape(5, 4)
b = a.clone() # clone a -> b
a, a + b

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]),
 tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [7]:
# 按元素乘法
a * b

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [8]:
x = torch.arange(4, dtype=torch.float32)
x, x.sum()

(tensor([0., 1., 2., 3.]), tensor(6.))

In [9]:
a.shape, a.sum()

(torch.Size([5, 4]), tensor(190.))

In [10]:
print(a)
a_sum_axis0 = a.sum(axis=0) # 按列求和
a_sum_axis0, a_sum_axis0.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([40., 45., 50., 55.]), torch.Size([4]))

In [11]:
print(a)
a_sum_axis1 = a.sum(axis=1) # 按行求和
a_sum_axis1, a_sum_axis1.shape

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])


(tensor([ 6., 22., 38., 54., 70.]), torch.Size([5]))

In [12]:
a.sum(axis=[0, 1]) # ~ a.sum()

tensor(190.)

In [13]:
# mean, average
a.mean(), a.sum() / a.numel()

(tensor(9.5000), tensor(9.5000))

In [14]:
# 按列求average
a.mean(axis=0), a.sum(axis=0) / a.shape[0]

(tensor([ 8.,  9., 10., 11.]), tensor([ 8.,  9., 10., 11.]))

In [15]:
y = torch.ones(4, dtype=torch.float32)
x = y.clone()
# 点基
print(x, '\n', y, torch.dot(x, y))

tensor([1., 1., 1., 1.]) 
 tensor([1., 1., 1., 1.]) tensor(4.)


In [16]:
# 矩阵乘法
print(a.size())
b = torch.ones(4, 3)
print(b.size())
print(torch.mm(a, b))


torch.Size([5, 4])
torch.Size([4, 3])
tensor([[ 6.,  6.,  6.],
        [22., 22., 22.],
        [38., 38., 38.],
        [54., 54., 54.],
        [70., 70., 70.]])


In [19]:
u = torch.tensor([3.0, -4.0]) 
print(torch.norm(u)) #L2: the length of a vector or a matrix
print(torch.abs(u).sum()) # L1: sum of abs(x)
print(torch.norm(torch.ones((4, 9)))) # F: matrix -> vector: L1

tensor(5.)
tensor(7.)
tensor(6.)
